services:
  app:
    build:
      context: .
    restart: unless-stopped

    environment:
      - ELEUTHERIA_APP_URL
    secrets:
      - app-secret-key
      - app-upgrade-key
      - db-password

    volumes:
      - app_images:/var/www/html/images
      - app_deleted_images:/var/www/data/deleted_images
      # Commentez cette ligne pour pouvoir initialiser la base de données en ligne. Puis suivez :
      # https://stackoverflow.com/questions/68267224/how-to-script-initializing-the-mediawiki-database-when-localsettings-php-already
      # Les valeurs qui sont données ne sont pas importantes, sauf utilisatrices et connections à la DB.
      - ./services/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - $ELEUTHERIA_PROXY_PORT:80

    healthcheck:
      test: netstat -an | grep :9000
      start_interval: 2s
      start_period: 3s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    restart: unless-stopped

    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: eleutheria
      MYSQL_USER: app
      MYSQL_PASSWORD: $ELEUTHERIA_DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    secrets:
      - db-password
      - db-ro-password

    volumes:
      - db:/var/lib/mysql
      - ./services/mariadb/init-user.sh:/docker-entrypoint-initdb.d/init-user.sh

    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      start_period: 3s
      start_interval: 2s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app_images:
  app_deleted_images:
  db:

secrets:
  app-secret-key:
    environment: ELEUTHERIA_APP_SECRET_KEY
  app-upgrade-key:
    environment: ELEUTHERIA_APP_UPGRADE_KEY
  db-password:
    environment: ELEUTHERIA_DB_PASSWORD
  db-ro-password:
    environment: ELEUTHERIA_DB_RO_PASSWORD
